-- ==============================================================================
-- DATABASE: procurement_db (Oracle PL/SQL)
-- DESCRIPTION: Hệ thống quản lý Mua hàng
-- ==============================================================================

ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = TCMART;

-- Lưu ý: Trong Oracle XE, các script này chạy dưới một user/schema (thường là tcmart).
-- Chúng ta không cần tạo schema/database riêng biệt bên trong script vì container tự tạo.
-- ------------------------------------------------------------------------------
-- 1. Bảng suppliers (Nhà cung cấp)
-- ------------------------------------------------------------------------------
CREATE TABLE suppliers (
    supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_code VARCHAR2(50) NOT NULL UNIQUE,
    supplier_name VARCHAR2(100),
    supplier_type VARCHAR2(100),
    tax_code VARCHAR2(50) NOT NULL UNIQUE,
    phone VARCHAR2(100),
    email VARCHAR2(100),
    address VARCHAR2(255),
    country NUMBER NOT NULL,
    status VARCHAR2(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
-- ------------------------------------------------------------------------------
-- 2. Bảng purchase_orders (Đơn đặt hàng mua)
-- ------------------------------------------------------------------------------
CREATE TABLE purchase_orders (
    purchase_order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_numder VARCHAR2(100) UNIQUE, -- Giữ nguyên tên cột po_numder từ docs
    supplier_id NUMBER NOT NULL,
    warehouse_id NUMBER NOT NULL,
    employee_id NUMBER NOT NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expected_date TIMESTAMP NOT NULL,
    currency_code VARCHAR2(50) NOT NULL,
    total_amount NUMBER(18,2) NOT NULL,
    status VARCHAR2(50) NOT NULL,
    CONSTRAINT fk_po_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id)
);
-- ------------------------------------------------------------------------------
-- 3. Bảng purchase_order_items (Chi tiết sản phẩm đơn PO)
-- ------------------------------------------------------------------------------
CREATE TABLE purchase_order_items (
    purchase_order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    ordered_quantity NUMBER NOT NULL,
    unit_price NUMBER(18,2) NOT NULL,
    tax_amount NUMBER(18,2) NOT NULL,
    discount_amount NUMBER(18,2) NOT NULL,
    line_amount NUMBER(18,2) NOT NULL,
    CONSTRAINT fk_po_items_po FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(purchase_order_id)
);
-- ------------------------------------------------------------------------------
-- 4. Bảng goods_receipts (Phiếu nhập kho)
-- ------------------------------------------------------------------------------
CREATE TABLE goods_receipts (
    goods_receipt_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_number VARCHAR2(50) NOT NULL UNIQUE,
    purchase_order_id NUMBER NOT NULL,
    warehouse_id NUMBER NOT NULL,
    receipt_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status VARCHAR2(50) NOT NULL,
    employee_id NUMBER NOT NULL,
    CONSTRAINT fk_gr_po FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(purchase_order_id)
);
-- ------------------------------------------------------------------------------
-- 5. Bảng goods_receipts_items (Chi tiết phiếu nhập kho)
-- ------------------------------------------------------------------------------
CREATE TABLE goods_receipt_items ( -- Sửa tên cho chuẩn danh từ số ít theo conventions
    goods_receipt_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goods_receipt_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    purchase_order_item_id NUMBER NOT NULL,
    ordered_quantity NUMBER NOT NULL,
    received_quantity NUMBER NOT NULL,
    rejected_quantity NUMBER NOT NULL,
    CONSTRAINT fk_gri_gr FOREIGN KEY (goods_receipt_id) REFERENCES goods_receipts(goods_receipt_id),
    CONSTRAINT fk_gri_poi FOREIGN KEY (purchase_order_item_id) REFERENCES purchase_order_items(purchase_order_item_id)
);
