-- ==============================================================================
-- DATABASE: warehouse_db (Oracle PL/SQL)
-- DESCRIPTION: Hệ thống quản lý Kho (Inventory)
-- ==============================================================================

ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = TCMART;

-- ------------------------------------------------------------------------------
-- 1. Bảng warehouses (Kho hàng)
-- ------------------------------------------------------------------------------
CREATE TABLE warehouses (
    warehouse_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_code VARCHAR2(50) NOT NULL UNIQUE,
    warehouse_name VARCHAR2(100),
    warehouse_type VARCHAR2(100),
    region VARCHAR2(50) NOT NULL,
    address VARCHAR2(255),
    capacity NUMBER NOT NULL,
    status VARCHAR2(50) NOT NULL
);
-- ------------------------------------------------------------------------------
-- 2. Bảng warehouse_locations (Vị trí trong kho)
-- ------------------------------------------------------------------------------
CREATE TABLE warehouse_locations (
    location_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id NUMBER NOT NULL,
    location_code VARCHAR2(50) NOT NULL UNIQUE,
    location_name VARCHAR2(100),
    zone VARCHAR2(100),
    CONSTRAINT fk_locations_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(warehouse_id)
);
-- ------------------------------------------------------------------------------
-- 3. Bảng inventory_transactions (Giao dịch thẻ kho)
-- ------------------------------------------------------------------------------
CREATE TABLE inventory_transactions (
    inventory_transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    transaction_type VARCHAR2(100),
    reference_type VARCHAR2(100),
    reference_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    employee_id NUMBER NOT NULL,
    CONSTRAINT fk_inv_trans_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(warehouse_id)
);
-- ------------------------------------------------------------------------------
-- 4. Bảng inventory (Tồn kho)
-- ------------------------------------------------------------------------------
CREATE TABLE inventory (
    inventory_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id NUMBER NOT NULL,
    location_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    reserved_quantity NUMBER NOT NULL,
    available_quantity NUMBER NOT NULL,
    last_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_inv_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(warehouse_id),
    CONSTRAINT fk_inv_location FOREIGN KEY (location_id) REFERENCES warehouse_locations(location_id)
);
-- ------------------------------------------------------------------------------
-- 5. Bảng stock_transfers (Lệnh điều chuyển kho)
-- ------------------------------------------------------------------------------
CREATE TABLE stock_transfers (
    transfer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_number VARCHAR2(50) NOT NULL UNIQUE,
    from_warehouse_id NUMBER NOT NULL,
    to_warehouse_id NUMBER NOT NULL,
    employee_id NUMBER NOT NULL,
    transfer_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status VARCHAR2(50) NOT NULL,
    CONSTRAINT fk_trf_from_wh FOREIGN KEY (from_warehouse_id) REFERENCES warehouses(warehouse_id),
    CONSTRAINT fk_trf_to_wh FOREIGN KEY (to_warehouse_id) REFERENCES warehouses(warehouse_id)
);
-- ------------------------------------------------------------------------------
-- 6. Bảng stock_transfer_items (Chi tiết sản phẩm điều chuyển)
-- ------------------------------------------------------------------------------
CREATE TABLE stock_transfer_items (
    transfer_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    CONSTRAINT fk_sti_transfer FOREIGN KEY (transfer_id) REFERENCES stock_transfers(transfer_id)
);
