-- ==============================================================================
-- DATABASE: production_db (Oracle PL/SQL)
-- DESCRIPTION: Hệ thống quản lý Sản xuất
-- ==============================================================================

ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = TCMART;

-- ------------------------------------------------------------------------------
-- 1. Bảng factories (Xưởng sản xuất)
-- ------------------------------------------------------------------------------
CREATE TABLE factories (
    factory_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factory_code VARCHAR2(50) NOT NULL UNIQUE,
    factory_name VARCHAR2(100),
    region VARCHAR2(50) NOT NULL,
    address VARCHAR2(255),
    capacity NUMBER NOT NULL,
    status VARCHAR2(50) NOT NULL
);
-- ------------------------------------------------------------------------------
-- 2. Bảng production_orders (Lệnh sản xuất)
-- ------------------------------------------------------------------------------
CREATE TABLE production_orders (
    production_order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_order_number VARCHAR2(50) NOT NULL UNIQUE,
    factory_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    employee_id NUMBER NOT NULL,
    planned_quantity NUMBER NOT NULL,
    actual_quantity NUMBER NOT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    status VARCHAR2(50) NOT NULL,
    CONSTRAINT fk_po_factory FOREIGN KEY (factory_id) REFERENCES factories(factory_id)
);
-- ------------------------------------------------------------------------------
-- 3. Bảng finished_products (Thành phẩm nhập kho)
-- ------------------------------------------------------------------------------
CREATE TABLE finished_products (
    finished_product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_order_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    production_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    warehouse_id NUMBER NOT NULL,
    CONSTRAINT fk_fp_order FOREIGN KEY (production_order_id) REFERENCES production_orders(production_order_id)
);
-- ------------------------------------------------------------------------------
-- 4. Bảng raw_materials (Nguyên vật liệu)
-- ------------------------------------------------------------------------------
CREATE TABLE raw_materials (
    material_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_code VARCHAR2(50) NOT NULL UNIQUE,
    material_name VARCHAR2(100),
    unit VARCHAR2(50)
);
-- ------------------------------------------------------------------------------
-- 5. Bảng production_order_items (Định mức nguyên liệu)
-- ------------------------------------------------------------------------------
CREATE TABLE production_order_items (
    production_order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_order_id NUMBER NOT NULL,
    material_id NUMBER NOT NULL,
    plan VARCHAR2(100),
    ned_quantity NUMBER NOT NULL,
    actual_quantity NUMBER NOT NULL,
    CONSTRAINT fk_poi_order FOREIGN KEY (production_order_id) REFERENCES production_orders(production_order_id),
    CONSTRAINT fk_poi_material FOREIGN KEY (material_id) REFERENCES raw_materials(material_id)
);
-- ------------------------------------------------------------------------------
-- 6. Bảng material_consumptions (Thực tế tiêu hao nguyên liệu)
-- ------------------------------------------------------------------------------
CREATE TABLE material_consumptions (
    consumption_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_order_id NUMBER NOT NULL,
    material_id NUMBER NOT NULL,
    employee_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    consumed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_mc_order FOREIGN KEY (production_order_id) REFERENCES production_orders(production_order_id),
    CONSTRAINT fk_mc_material FOREIGN KEY (material_id) REFERENCES raw_materials(material_id)
);
