"""
gen_procurement.py — Data Generator cho procurement_db (Oracle)
Phụ thuộc: product_db (lấy product_id), employee_db (lấy employee_id), warehouse_db (lấy warehouse_id)
"""
import sys
import os
import random
from sqlalchemy import text
from datetime import timedelta

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from config import ORACLE_URL, PG_BASE_URL, GEN_CONFIG
from generators.base import BaseGenerator
from sqlalchemy import create_engine


class ProcurementGenerator(BaseGenerator):
    def __init__(self):
        super().__init__(ORACLE_URL)
        self.pg_engine = create_engine(PG_BASE_URL.format(db="postgres"))

    def get_master_data(self):
        product_ids = []
        employee_ids = []
        with self.pg_engine.connect() as conn:
            res_prod = conn.execute(text("SELECT product_id, cost_price FROM product_db.products WHERE status='active'"))
            product_ids = [{"id": r[0], "cost": float(r[1])} for r in res_prod.fetchall()]
            
            res_emp = conn.execute(text("SELECT employee_id FROM employee_db.employees WHERE status='active'"))
            employee_ids = [r[0] for r in res_emp.fetchall()]
            
        return product_ids, employee_ids

    def run(self):
        print("Generating data for procurement_db (Oracle)...")
        products, employees = self.get_master_data()
        if not products or not employees:
            print("❌ Lỗi: Cần chạy gen_product.py và gen_employee.py trước!")
            return

        # Disable foreign key checks isn't straightforward in Oracle without dropping, so we delete in correct order
        with self.engine.connect() as conn:
            conn.execute(text("DELETE FROM goods_receipt_items"))
            conn.execute(text("DELETE FROM goods_receipts"))
            conn.execute(text("DELETE FROM purchase_order_items"))
            conn.execute(text("DELETE FROM purchase_orders"))
            conn.execute(text("DELETE FROM suppliers"))
            conn.commit()
        
        with self.get_session() as session:
            # 1. Suppliers
            num_suppliers = GEN_CONFIG.get("num_suppliers", 50)
            supplier_ids = []
            for i in range(1, num_suppliers + 1):
                res = session.execute(
                    text("""
                        INSERT INTO suppliers (supplier_code, supplier_name, supplier_type, tax_code, phone, email, address, country, status)
                        VALUES (:code, :name, :type, :tax, :phone, :email, :addr, :country, 'active')
                    """),
                    {
                        "code": f"SUP-{i:03d}",
                        "name": f"NCC {self.fake.company()}",
                        "type": random.choice(["Local", "International"]),
                        "tax": self.fake.ean(length=13)[:10],
                        "phone": self.vn_phone(),
                        "email": self.fake.company_email(),
                        "addr": self.fake.address(),
                        "country": random.choice([84, 1, 86, 81]), # 84: VN, 1: US, 86: CN, 81: JP
                    }
                )
                # Oracle with SQLAlchemy using RETURNING is tricky depending on driver. 
                # Let's just query it back or use sequence if generated by default as identity.
                # Since we don't have OUT binds easily setup in raw text(), we can just rely on fetching the ID.
                # Actually, simpler is to just insert, then fetch all IDs.
            session.commit()
            
            # Fetch all supplier IDs
            res = session.execute(text("SELECT supplier_id FROM suppliers"))
            supplier_ids = [r[0] for r in res.fetchall()]
            print(f" - Inserted {len(supplier_ids)} suppliers.")

            # 2. Purchase Orders
            num_pos = GEN_CONFIG.get("num_purchase_orders", 500)
            po_ids = []
            for i in range(1, num_pos + 1):
                sup_id = random.choice(supplier_ids)
                order_date = self.fake.date_time_this_year()
                
                po_products = random.sample(products, k=random.randint(1, 10))
                subtotal = 0
                items_data = []
                for p in po_products:
                    qty = random.randint(100, 1000)
                    unit_price = p["cost"] * 0.9 # Mua vào rẻ hơn giá vốn chuẩn
                    tax = unit_price * qty * 0.08
                    line_amount = (unit_price * qty) + tax
                    subtotal += unit_price * qty
                    
                    items_data.append({
                        "product_id": p["id"], "quantity": qty, "unit_price": unit_price,
                        "tax": tax, "discount": 0, "line_amount": line_amount
                    })
                
                total_amount = subtotal * 1.08
                
                session.execute(
                    text("""
                        INSERT INTO purchase_orders (po_numder, supplier_id, warehouse_id, employee_id, order_date, expected_date, currency_code, total_amount, status)
                        VALUES (:num, :sid, :wid, :eid, :date, :exp, 'VND', :total, :status)
                    """),
                    {
                        "num": f"PO-{order_date.strftime('%Y%m%d')}-{i:04d}",
                        "sid": sup_id,
                        "wid": random.randint(1, 5), # warehouse 1-5
                        "eid": random.choice(employees),
                        "date": order_date,
                        "exp": order_date + timedelta(days=random.randint(7, 30)),
                        "total": total_amount,
                        "status": random.choice(["Completed", "Pending", "Approved"])
                    }
                )
            session.commit()
            
            # Since we didn't use RETURNING, let's fetch POs to create items
            pos = session.execute(text("SELECT purchase_order_id, status, warehouse_id, employee_id FROM purchase_orders")).fetchall()
            print(f" - Inserted {len(pos)} purchase orders.")
            
            for po in pos:
                po_id = po[0]
                po_status = po[1]
                po_wid = po[2]
                po_eid = po[3]
                
                po_products = random.sample(products, k=random.randint(1, 5))
                for p in po_products:
                    qty = random.randint(100, 1000)
                    up = p["cost"] * 0.9
                    tax = up * qty * 0.08
                    line_amt = up * qty + tax
                    session.execute(
                        text("""
                            INSERT INTO purchase_order_items (purchase_order_id, product_id, ordered_quantity, unit_price, tax_amount, discount_amount, line_amount)
                            VALUES (:pid, :prod, :qty, :up, :tax, 0, :amt)
                        """),
                        {"pid": po_id, "prod": p["id"], "qty": qty, "up": up, "tax": tax, "amt": line_amt}
                    )
                
                # 3. Goods Receipts (if PO is Completed)
                if po_status == 'Completed':
                    session.execute(
                        text("""
                            INSERT INTO goods_receipts (receipt_number, purchase_order_id, warehouse_id, status, employee_id)
                            VALUES (:num, :pid, :wid, 'Received', :eid)
                        """),
                        {
                            "num": f"GR-{po_id}",
                            "pid": po_id, "wid": po_wid, "eid": po_eid
                        }
                    )
            session.commit()
            print(" - Inserted purchase order items and goods receipts.")
            
            # 4. Goods receipt items
            grs = session.execute(text("SELECT goods_receipt_id, purchase_order_id FROM goods_receipts")).fetchall()
            for gr in grs:
                gr_id = gr[0]
                po_id = gr[1]
                # Get PO items
                poi = session.execute(text("SELECT purchase_order_item_id, product_id, ordered_quantity FROM purchase_order_items WHERE purchase_order_id=:pid"), {"pid": po_id}).fetchall()
                for item in poi:
                    session.execute(
                        text("""
                            INSERT INTO goods_receipt_items (goods_receipt_id, product_id, purchase_order_item_id, ordered_quantity, received_quantity, rejected_quantity)
                            VALUES (:grid, :prod, :poi_id, :oq, :rq, 0)
                        """),
                        {"grid": gr_id, "prod": item[1], "poi_id": item[0], "oq": item[2], "rq": item[2]}
                    )
            session.commit()
            print(" - Inserted goods receipt items.")

if __name__ == "__main__":
    generator = ProcurementGenerator()
    generator.run()
