FROM apache/airflow:2.9.3-python3.10

USER root
# Cài đặt Java (Bắt buộc để chạy PySpark)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    default-jre-headless \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow
# Cài đặt PySpark
RUN pip install --no-cache-dir pyspark==3.5.1
